---
application:
  name: "kanboard"
  project: "Todo"
  organization: "QoveryCommunity"
  storage:
  - name: "todo"
    size: "10"
    type: "fast_ssd"
    mount_point: "/mnt/todo"
routers:
- name: "main-kanboard"
  routes:
  - application_name: "kanboard"
    paths:
    - "/*"
